# Generated by Django 3.0 on 2022-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bay_admin', 'Bay Admin'), ('shipping_admin', 'Shipping Admin'), ('user', 'User')], max_length=250, verbose_name='role'),
        ),
    ]
