# Generated by Django 3.0 on 2022-02-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0002_auto_20220224_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.AddField(
            model_name='user',
            name='bay_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bay_admins', to='main.BayArea'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_admins', to='main.ShippingCompany'),
        ),
    ]
