# Generated by Django 3.0 on 2022-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
    ]
