# Generated by Django 3.0 on 2022-04-26 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bayarea_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayarea',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bayarea',
            name='phone',
            field=models.CharField(default='+2345960495943', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='address',
            field=models.CharField(default='no address yet', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='opening_hours',
            field=models.CharField(default='no idea', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='phone',
            field=models.CharField(default='+2345960495943', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
