# Generated by Django 3.0 on 2022-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220426_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='freedays',
            field=models.IntegerField(default=0),
        ),
    ]
