# Generated by Django 3.0 on 2022-05-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shippingcompany_freedays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcompany',
            name='freedays',
        ),
    ]
