# Generated by Django 3.0 on 2022-04-28 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_shippingcompany_freedays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demurage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('price_per_day', models.FloatField()),
                ('size', models.CharField(choices=[('20 feet', '20 feet'), ('40 feet', '40 feet')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demurages', to='main.ShippingCompany')),
            ],
        ),
    ]
