# Generated by Django 3.0 on 2022-05-23 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demurage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemurageSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demurage',
            name='size',
        ),
    ]
