# Generated by Django 3.0 on 2022-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demurage', '0004_auto_20220523_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='demurage',
            name='demurage_type',
            field=models.CharField(blank=True, choices=[('import', 'Import'), ('export', 'Export')], max_length=250, null=True),
        ),
    ]
