# Generated by Django 3.0 on 2022-08-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_shippingcompany_freedays'),
        ('demurage', '0005_demurage_demurage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demuragesize',
            name='container_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demuragesize',
            name='shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demurage_size', to='main.ShippingCompany'),
        ),
        migrations.AlterField(
            model_name='demuragesize',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
