# Generated by Django 3.0 on 2022-10-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demurage', '0006_auto_20220810_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemurrageCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('container_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('chargeable_days', models.IntegerField(default=0)),
                ('free_days', models.IntegerField()),
                ('amount', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('total', models.FloatField()),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
