# Generated by Django 3.0 on 2022-11-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_shippingcompany_freedays'),
        ('demurage', '0007_demurragecalculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='demurragecalculations',
            name='shipping_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ShippingCompany'),
        ),
    ]
