# Generated by Django 3.0 on 2022-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_off',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
