# Generated by Django 3.0 on 2022-04-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20220226_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_created']},
        ),
    ]
