# Generated by Django 3.0 on 2022-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220426_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='container_size',
            field=models.CharField(choices=[('20 feet', '20 feet'), ('40 feet', '40 feet')], max_length=350),
        ),
    ]
