# Generated by Django 3.0 on 2022-07-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20220428_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
